---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WJC.
--- DateTime: 2025-01-27 21:44
---

-- 参数列表: 优惠券id，用户id，订单orderId
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]
local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId
-- 1.判断库存是否充足
-- 因为redis的get命令得到的字符串，要跟0比较，需用tonumber函数转为数字
if(tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end
-- 2.判断用户是否下过单
if(redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
-- 3.扣减库存
redis.call('incrby', stockKey, -1)
-- 4.将userId存入当前优惠券的set集合
redis.call('sadd', orderKey, userId)
-- 5.将voucherId、userId、orderId发至消息队列    xadd * k1 v1 k2 v2
redis.call('xadd', 'stream.orders',  '*', 'voucherId', voucherId, 'userId', userId, 'id', orderId)
return 0
